### ISSUE TITLE
Source code for ech-check.php

### ISSUE THREAD

**Issue by kovalensky** [defo-project/ech-dev-utils#4]
Hello, thank you for amazing initiative developing ECH.

I was wondering if code for ECH check is available for general use?

**Comment by sftcd** [comment]
hiya - sure, added a version of that [here](https://github.com/defo-project/ech-dev-utils/blob/main/scripts/ech-check.php)

**Comment by kovalensky** [comment]
Thanks 👍🏻

The way I see it, after installing nginx via [Guardian tutorial](https://guardianproject.info/2023/11/10/quick-set-up-guide-for-encrypted-client-hello-ech/), the _SSL_ECH_*_ variables should appear in $_SERVER array automatically, or do we have to use additional nginx configuration?

**Comment by sftcd** [comment]
> Thanks 👍🏻
> 
> The way I see it, after installing nginx via Guardian
> tutorial<https://guardianproject.info/2023/11/10/quick-set-up-guide-for-encrypted-client-hello-ech/>,
> the SSL_ECH*_ variables should appear in $_SERVER array
> automatically, or do we have to use additional nginx configuration?
> 

You need to have configured those in your nginx config with
something like:

```
     fastcgi_param SSL_ECH_STATUS $ssl_ech_status;
     fastcgi_param SSL_ECH_INNER_SNI $ssl_ech_inner_sni;
     fastcgi_param SSL_ECH_OUTER_SNI $ssl_ech_outer_sni;
```

Cheers,
S.

**Comment by kovalensky** [comment]
I see, thank you for the tips 💪🏻🙂
